language: android

jdk:
    - oraclejdk8

android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    # SDK Version
    - android-15
    - android-25
